### ISSUE TITLE
关于在arq的task中使用sanic的相关业务函数的问题

### ISSUE THREAD

**Issue by yodew** [bdwallace/SanicDemo#1]
请问一下，目前我对sanic和arq的集成已经搞定， 由于我的tortoise-orm是与sanic集成的，我如何在arq的task中使用相关orm的函数？

**Comment by bdwallace** [comment]
1.首先是arq任务函数定义的格式：async def test_task(ctx)
2.其次要在WorkerSettings.functions中添加该函数

**Comment by bdwallace** [comment]
3.最后函数在视图中的调用:await arq.enqueue_job("testdemo")

**Comment by bdwallace** [comment]
3.最后函数在视图中的调用:
from core import get_arq_obj
arq = await get_arq_obj()
await arq.enqueue_job("testdemo")

**Comment by bdwallace** [comment]
平时怎么使用orm，在任务函数中就怎么使用，没有区别

**Comment by bdwallace** [comment]
![image](https://github.com/bdwallace/SanicDemo/assets/84302113/dea248d6-c715-42cc-97fe-af32092e6f43)
